### ISSUE TITLE
How to use this npm?

### ISSUE THREAD

**Issue by mingkunm** [bennymeg/AcademicEmailVerifier#2]
Hi,

When I use:
const verifier = require('academic-email-verifier');
let isAcademic = await verifier.isAcademic(email);

terminal will raise these error:
UnhandledPromiseRejectionWarning: TypeError: verifier.isAcademic is not a function

It means isAcademic is not a function, and when I use:
import { Verifier } from 'academic-email-verifier';

the error will be:
import { Verifier } from 'academic-email-verifier';
^^^^^^

SyntaxError: Cannot use import statement outside a module

How can I solve it?

Thank you!

**Comment by vwinstea** [comment]
After messing around with this package it turns out the correct way to import this is 
`const verifier = require('academic-email-verifier').Verifier`
I have no idea why this works, but this should fix any import errors you are having

**Comment by bennymeg** [comment]
As stated by documentation you import the verifier as such:
`import { Verifier } from 'academic-email-verifier';`

If you wish to require it, you can use the following statement:
`const verifier = require('academic-email-verifier').Verifier`
